### ISSUE TITLE
Notification.show should show a notification

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-notification-flow#13]
```
Notification.show("Hello", 1000, Position.MIDDLE);
```

Expected result:
A notification saying "Hello" is shown in the middle of the screen

Actual result:
Nothing is shown. The notification is never attached to the DOM

**Comment by heruan** [comment]
Also the demo is misleading:

<img width="827" alt="screen shot 2018-01-16 at 18 29 20" src="https://user-images.githubusercontent.com/851745/35002899-65d4ed4e-faeb-11e7-9b16-cc0b0efea930.png">

 since it seems that this code

```java
Notification notification = new Notification(
        "This notification has text content", 3000);
button.addClickListener(event -> notification.open());
```

is enough to show the notification, without attaching it to the DOM.

Maybe not just the static method, but the constructor itself should attach the element to the DOM?

**Comment by alvarezguille** [comment]
`new Button("Click me", event -> Notification.show("Clicked!", 3000, Position.TOP_CENTER))`
Seems to work just fine for me with latest versions

* vaadin-notification-flow: 1.0.0.alpha6
* flow: 1.0.0.alpha20

**Comment by denis-anisimov** [comment]
This is already fixed.
The reason is that the developer should add notification as a component to some attached parent.
Only after this `open`  method opens the notification.
Previously it has been required that this addition should have been done manually.
Now the `open()` method auto adds the notification to the `UI` instance if it's not added yet.
