### ISSUE TITLE
Component support for Notification

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-notification-flow#2]
### Acceptance Criteria
- There is a demo on `Notification` for showing how to put components inside it that the user can interact with
- There is an _alpha_ release of the component I can use

**Comment by heruan** [comment]
Why leaving support for plain HTML content? I see it as an anti-pattern with the Flow philosophy of *all is a component*, plus the `setContent(String content)` is confusing then.

**Comment by pleku** [comment]
> Great to have support for components! Curiosity: why leaving support for plain HTML content? I see it as an anti-pattern with the Flow philosophy of all is a component, plus the setContent(String content) is confusing then.

Sometimes it might be a bit _overkill_ to create components just for static HTML.  Often the notifications shown have only static content. 

Probably we could split the current `setContent()` to text / html. The javadoc is very bad at the moment, it doesn't state what happens when you mix `setContent` and components..
I think for the simple text use case e.g.
`notification.setText("New Message"); or Notification.show("New Message");`
is much more handy than
`notification.add(new Text("New  Message"); or Notification.show(new Text("New Message");`
The same works for HTML as `String` versus the `Html` component. Often you want to e.g. easily show notification with text on multiple rows, I think there just using plain html can be quite fast and efficient. For that we could add `setInnerHtml()`.

What does @Legioth think ?

**Comment by heruan** [comment]
The same holds for other components such as `Dialog`, `H1`-`H6`, `Paragraph`, *`List`. Why not using a HTML component or template renderer, to use plain HTML as a string in all that cases?

**Comment by pleku** [comment]
A template renderer seems to me a total overkill and even confusing when there is no items repeating nor there is a template in the component to use for binding.

**Comment by Legioth** [comment]
For "regular" components without wrapping `<template>` elements, the primary way of defining the contents of the component is through `HasComponents.add` and/or `HasText.setText`. Any other mechanism is currently custom for that particular component.

Some components such as `Dialog` or `Notification` require a `<template>` that is manually stamped out in some other part of the DOM. Whenever reasonable, we should make such components behave in the same way as "regular" components. Among other things, this means that these components should also implement `HasComponents` and `HasText`, even though the default implementations from those interfaces would have to be overridden.

Missing is a convenient and unified way of providing an arbitrary blob of HTML content. This is mostly needed for formatted text since it's not convenient nor appropriate to use individual component instances for content like `Hello <em>world</em>`. Using the `HTML` component is somewhat boilerplatey and not always feasible since it requires exactly one child element. Manually assigning the `innerHTML` property requires boilerplate and must be done in different ways for "regular" and `<template>` components. An additional complication with `innerHTML` is that `<template>` components would have special treatment for some tokens in the contents (e.g. `{{` and `[[`) whereas "regular" components would render those as-is.

I think we would need a low level helper API for consistently setting a HTML blob as the content of any component, regardless of whether it's a "regular" component or based on `<template>`. In addition, components that are typically expected to be used with formatted contents (e.g. `Paragraph` and `Notification`) could implement a `HasHtml` marker interface that provides a shorthand `setHtml` method. This kind of functionality also begs for some way of constructing HTML snippets where some parts are escaped for XSS protection whereas other parts of the snippet are considered trusted.

One detail that is slightly unclear with official `setHtml` support is how this content works in relationship to the regular DOM API, e.g. `getChildCount()`, `inserChild(0, additionalChild)`,  or `removeAllChildren()`. This is already slightly unclear when setting the `innerHTML` property, but the weird behaviour in that case can be excused by the hackish nature of using the special property.

Particularly for this ticket, I would recommend that we remove explicit support for setting a HTML string as the content of a `Notification` and instead only expose `setText` and child component support. HTML content should instead be set with the overhead of a `HTML` component or through a not-yet-implemented common mechanism that works the same regardless of the component type.

**Comment by iatomic** [comment]
this discussion is a nice overkill but I hope it leads someplace :-). Now, I want to line breaks into a text that is part of a ...say...label....

"This is my text <br/> Heloo"

how to do this in Vaadin withthou some IMMENSE OVERKILL?
